-- Crea Secuencia Solicitud --
CREATE SEQUENCE BODEGA.JSYB_BG_NRO_SOL_MEMO
MINVALUE 1 MAXVALUE 999999999999999999999999999
INCREMENT BY 1 START WITH 1
NOCACHE NOORDER NOCYCLE;

-- Crea Tabla Cabecera --
---DROP TABLE BODEGA.JSYB_BG_SOLICITUD_MEMO_TL CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_SOLICITUD_MEMO_TL (
    SOLICITUD_ID         NUMBER NOT NULL,
    CODIGO_EMPRESA       NUMBER NOT NULL,
    LO_CODIGO            NUMBER,
    ORIGEN               VARCHAR2(10 BYTE) NOT NULL,
    DESCRIPCION          VARCHAR2(50 BYTE) NOT NULL,
    ESTADO               VARCHAR2(10 BYTE) NOT NULL,
    MOTIVO               VARCHAR2(10 BYTE) NOT NULL,
    REASON_ID            NUMBER NOT NULL,
    NUM_MEMO             NUMBER,
    CANTIDAD_MAX         NUMBER,
    USUARIO_REGISTRO     VARCHAR2(100 BYTE) NOT NULL,
    FECHA_REGISTRO       DATE NOT NULL,
    USUARIO_ULTIMA_ACT   VARCHAR2(100 BYTE) NOT NULL,
    FECHA_ULTIMA_ACT     DATE NOT NULL,
    CONSTRAINT JSYB_BG_SOLICITUD_MEMO_PK PRIMARY KEY ( SOLICITUD_ID,CODIGO_EMPRESA )
);

-- Crea Tabla Detalle --
---DROP TABLE BODEGA.JSYB_BG_DET_SOLICITUD_MEMO_TL CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_DET_SOLICITUD_MEMO_TL (
    SOLICITUD_ID        NUMBER NOT NULL,
    CODIGO_EMPRESA      NUMBER NOT NULL,
    ORG_ID_INV          NUMBER NOT NULL,
    INVENTORY_ITEM_ID   NUMBER NOT NULL,
    CODIGO_LOTE         VARCHAR2(40 BYTE),
    CANTIDAD_MAX        NUMBER,
    CONSTRAINT JSYB_BG_DET_SOLICITUD_MEMO_PK UNIQUE ( SOLICITUD_ID,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE )
);

-- Crea Tabla Locales Cabecera --
---DROP TABLE BODEGA.JSYB_BG_LOC_SOLICITUD_MEMO_TL CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_LOC_SOLICITUD_MEMO_TL (
    SOLICITUD_ID     NUMBER NOT NULL,
    CODIGO_EMPRESA   NUMBER NOT NULL,
    LO_CODIGO        NUMBER NOT NULL,
    CANTIDAD_MAX     NUMBER,
    CONSTRAINT JSYB_BG_LOC_SOLICITUD_MEMO_PK PRIMARY KEY ( SOLICITUD_ID,CODIGO_EMPRESA,LO_CODIGO )
);

-- Crea Tabla Locales Detalle --
---DROP TABLE BODEGA.JSYB_BG_LOD_SOLICITUD_MEMO_TL CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_LOD_SOLICITUD_MEMO_TL (
    SOLICITUD_ID        NUMBER NOT NULL,
    CODIGO_EMPRESA      NUMBER NOT NULL,
    ORG_ID_INV          NUMBER NOT NULL,
    INVENTORY_ITEM_ID   NUMBER NOT NULL,
    CODIGO_LOTE         VARCHAR2(40),
    LO_CODIGO           NUMBER NOT NULL,
    CANTIDAD_MAX        NUMBER,
    CONSTRAINT JSYB_BG_LOD_SOLICITUD_MEMO_PK UNIQUE ( SOLICITUD_ID,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE,LO_CODIGO )
);


-- Crea Tabla Temporal Cabecera --
---DROP TABLE BODEGA.JSYB_BG_TEMP_ENC_SOL_MEMO CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_TEMP_ENC_SOL_MEMO (
    SOLICITUD_ID         NUMBER NOT NULL,
    CODIGO_EMPRESA       NUMBER NOT NULL,
    LO_CODIGO            NUMBER,
    ORIGEN               VARCHAR2(10 BYTE),
    DESCRIPCION          VARCHAR2(50 BYTE),
    ESTADO               VARCHAR2(10 BYTE),
    MOTIVO               VARCHAR2(10 BYTE),
    REASON_ID            NUMBER,
    NUM_MEMO             NUMBER,
    CANTIDAD_MAX         NUMBER,
    CONSTRAINT JSYB_BG_TEMP_ENC_SOL_MEMO_PK PRIMARY KEY ( SOLICITUD_ID,CODIGO_EMPRESA )
);

-- Crea Tabla Temporal Detalle --
---DROP TABLE BODEGA.JSYB_BG_TEMP_DET_SOL_MEMO CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_TEMP_DET_SOL_MEMO (
    SOLICITUD_ID        NUMBER NOT NULL,
    CODIGO_EMPRESA      NUMBER NOT NULL,
    ORG_ID_INV          NUMBER NOT NULL,
    INVENTORY_ITEM_ID   NUMBER NOT NULL,
    CODIGO_LOTE         VARCHAR2(40 BYTE),
    CANTIDAD_MAX        NUMBER,
    FILA_ELIMINADA      VARCHAR2(1),
    CONSTRAINT JSYB_BG_TEMP_DET_SOL_MEMO_PK UNIQUE ( SOLICITUD_ID,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE )
);

-- Crea Tabla Temporal Locales Cabecera --
---DROP TABLE BODEGA.JSYB_BG_TEMP_LOC_SOL_MEMO CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_TEMP_LOC_SOL_MEMO (
    SOLICITUD_ID        NUMBER NOT NULL,
    CODIGO_EMPRESA  NUMBER NOT NULL,
    LO_CODIGO       NUMBER NOT NULL,
    CANTIDAD_MAX    NUMBER,
    FILA_ELIMINADA      VARCHAR2(1),
    CONSTRAINT JSYB_BG_TEMP_LOC_SOL_MEMO_PK PRIMARY KEY ( SOLICITUD_ID,CODIGO_EMPRESA,LO_CODIGO )
);

-- Crea Tabla Temporal Locales Detalle --
---DROP TABLE BODEGA.JSYB_BG_TEMP_LOD_SOL_MEMO CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_TEMP_LOD_SOL_MEMO (
    SOLICITUD_ID            NUMBER NOT NULL,
    CODIGO_EMPRESA      NUMBER NOT NULL,
    ORG_ID_INV          NUMBER NOT NULL,
    INVENTORY_ITEM_ID   NUMBER NOT NULL,
    CODIGO_LOTE         VARCHAR2(40),
    LO_CODIGO           NUMBER NOT NULL,
    CANTIDAD_MAX        NUMBER,
    FILA_ELIMINADA      VARCHAR2(1),
    CONSTRAINT JSYB_BG_TEMP_LOD_SOL_MEMO_PK UNIQUE ( SOLICITUD_ID,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE,LO_CODIGO )
);

-- Crea Tabla Temporal Carga Archivo --
---DROP TABLE BODEGA.JSYB_BG_TEMP_CAR_SOL_MEMO CASCADE CONSTRAINTS;
CREATE GLOBAL TEMPORARY TABLE BODEGA.JSYB_BG_TEMP_CAR_SOL_MEMO (
    SOLICITUD_ID            NUMBER,
    INVENTORY_ITEM_ID   NUMBER,
    REASON_ID           NUMBER,
    CODIGO_LOTE         VARCHAR2(40),
    LO_CODIGO           NUMBER,
    CANTIDAD_MAX        NUMBER
) ON COMMIT PRESERVE ROWS ;


-- Crea Foreign Cabezera-Detalle --
ALTER TABLE BODEGA.JSYB_BG_DET_SOLICITUD_MEMO_TL ADD CONSTRAINT JSYB_BG_ENC_DET_SOL_MEMO_FK FOREIGN KEY ( SOLICITUD_ID,CODIGO_EMPRESA )
REFERENCES BODEGA.JSYB_BG_SOLICITUD_MEMO_TL ( SOLICITUD_ID,CODIGO_EMPRESA );

-- Crea Foreign Cabezera-Locales --
ALTER TABLE JSYB_BG_LOC_SOLICITUD_MEMO_TL ADD CONSTRAINT JSYB_BG_ENC_LOC_SOL_MEMO_FK FOREIGN KEY ( SOLICITUD_ID,CODIGO_EMPRESA )
REFERENCES BODEGA.JSYB_BG_SOLICITUD_MEMO_TL ( SOLICITUD_ID,CODIGO_EMPRESA );

-- Crea Foreign Detalle-Locales --
ALTER TABLE BODEGA.JSYB_BG_LOD_SOLICITUD_MEMO_TL ADD CONSTRAINT JSYB_BG_DET_LOD_SOL_MEMO_FK FOREIGN KEY ( SOLICITUD_ID,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE )
REFERENCES BODEGA.JSYB_BG_DET_SOLICITUD_MEMO_TL ( SOLICITUD_ID,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE );

-- Crea Foreign Solicitud-Memo --
ALTER TABLE BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL ADD CONSTRAINT JSYB_BG_SOL_MEMO_FK FOREIGN KEY ( SOLICITUD_ID, CODIGO_EMPRESA )
REFERENCES BODEGA.JSYB_BG_SOLICITUD_MEMO_TL ( SOLICITUD_ID,CODIGO_EMPRESA );

-- Crea Grants de Tablas y Secuencia --
GRANT ALL ON BODEGA.JSYB_BG_NRO_SOL_MEMO TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_SOLICITUD_MEMO_TL TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_DET_SOLICITUD_MEMO_TL TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_LOC_SOLICITUD_MEMO_TL TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_LOD_SOLICITUD_MEMO_TL TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_TEMP_ENC_SOL_MEMO TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_TEMP_DET_SOL_MEMO TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_TEMP_LOC_SOL_MEMO TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_TEMP_LOD_SOL_MEMO TO SYBAPPS;
GRANT SELECT ON BODEGA.JSYB_BG_TEMP_CAR_SOL_MEMO TO SYBAPPS;

-- Crea Sinonimos de Tablas y Secuencia --
CREATE SYNONYM SYBAPPS.JSYB_BG_NRO_SOL_MEMO FOR BODEGA.JSYB_BG_NRO_SOL_MEMO;
CREATE SYNONYM SYBAPPS.JSYB_BG_SOLICITUD_MEMO_TL FOR BODEGA.JSYB_BG_SOLICITUD_MEMO_TL;
CREATE SYNONYM SYBAPPS.JSYB_BG_DET_SOLICITUD_MEMO_TL FOR BODEGA.JSYB_BG_DET_SOLICITUD_MEMO_TL;
CREATE SYNONYM SYBAPPS.JSYB_BG_LOC_SOLICITUD_MEMO_TL FOR BODEGA.JSYB_BG_LOC_SOLICITUD_MEMO_TL;
CREATE SYNONYM SYBAPPS.JSYB_BG_LOD_SOLICITUD_MEMO_TL FOR BODEGA.JSYB_BG_LOD_SOLICITUD_MEMO_TL;
CREATE SYNONYM SYBAPPS.JSYB_BG_TEMP_ENC_SOL_MEMO FOR BODEGA.JSYB_BG_TEMP_ENC_SOL_MEMO;
CREATE SYNONYM SYBAPPS.JSYB_BG_TEMP_DET_SOL_MEMO FOR BODEGA.JSYB_BG_TEMP_DET_SOL_MEMO;
CREATE SYNONYM SYBAPPS.JSYB_BG_TEMP_LOC_SOL_MEMO FOR BODEGA.JSYB_BG_TEMP_LOC_SOL_MEMO;
CREATE SYNONYM SYBAPPS.JSYB_BG_TEMP_LOD_SOL_MEMO FOR BODEGA.JSYB_BG_TEMP_LOD_SOL_MEMO;
CREATE SYNONYM SYBAPPS.JSYB_BG_TEMP_CAR_SOL_MEMO FOR BODEGA.JSYB_BG_TEMP_CAR_SOL_MEMO;