-- Crea Secuencia Memo --
---DROP SEQUENCE BODEGA.JSYB_BG_NRO_MEMO_DEVOL;
declare
    vl_new_seq NUMBER;
begin
    select   max(num_memo)+1 into vl_new_seq
        from BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL;

    execute immediate   'CREATE SEQUENCE BODEGA.JSYB_BG_NRO_MEMO_DEVOL '||
                        'MINVALUE 1 MAXVALUE 999999999999999999999999999 '||
                        'INCREMENT BY 1 START WITH '||vl_new_seq||' '||
                        'NOCACHE NOORDER NOCYCLE';
end;
/

-- Crea Tabla Locales Cabecera --
---DROP TABLE BODEGA.JSYB_BG_LOC_MEMO_DEVOLUCION_TL CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_LOC_MEMO_DEVOLUCION_TL (
    NUM_MEMO        NUMBER NOT NULL,
    CODIGO_EMPRESA  NUMBER NOT NULL,
    LO_CODIGO       NUMBER NOT NULL,
    CANTIDAD_MAX    NUMBER,
    CONSTRAINT JSYB_BG_LOC_MEMO_DEVOLUCION_PK PRIMARY KEY ( NUM_MEMO,CODIGO_EMPRESA,LO_CODIGO )
);

-- Crea Tabla Locales Detalle --
---DROP TABLE BODEGA.JSYB_BG_LOD_MEMO_DEVOLUCION_TL CASCADE CONSTRAINTS;
CREATE TABLE BODEGA.JSYB_BG_LOD_MEMO_DEVOLUCION_TL (
    NUM_MEMO            NUMBER NOT NULL,
    CODIGO_EMPRESA      NUMBER NOT NULL,
    ORG_ID_INV          NUMBER NOT NULL,
    INVENTORY_ITEM_ID   NUMBER NOT NULL,
    CODIGO_LOTE         VARCHAR2(40),
    LO_CODIGO           NUMBER NOT NULL,
    CANTIDAD_MAX        NUMBER,
    CONSTRAINT JSYB_BG_LOD_MEMO_DEVOLUCION_PK UNIQUE ( NUM_MEMO,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE,LO_CODIGO )
);


-- Crea Tabla Temporal Carga Archivo --
---DROP TABLE BODEGA.JSYB_BG_TEMP_CAR_MEMO_DEVOL CASCADE CONSTRAINTS;
CREATE GLOBAL TEMPORARY TABLE BODEGA.JSYB_BG_TEMP_CAR_MEMO_DEVOL (
    NUM_MEMO            NUMBER,
    INVENTORY_ITEM_ID   NUMBER,
    REASON_ID           NUMBER,
    CODIGO_LOTE         VARCHAR2(40),
    LO_CODIGO           NUMBER,
    CANTIDAD_MAX        NUMBER,
    COD_PRODUCTO        VARCHAR2(40)
) ON COMMIT PRESERVE ROWS ;


-- Elimina Detalles Sin Cabecera --
DELETE  BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL det
WHERE   (det.NUM_MEMO,det.CODIGO_EMPRESA) NOT IN (SELECT    enc.NUM_MEMO,enc.CODIGO_EMPRESA
                                                    FROM    BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL enc);
commit;


-- Agrega Columnas en Cabecera --
ALTER TABLE BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL ADD (
    MOTIVO              VARCHAR2(10),
    SOLICITUD_ID        NUMBER,
    CANTIDAD_MAX        NUMBER,
    USUARIO_REGISTRO    VARCHAR2(100),
    FECHA_REGISTRO      DATE,
    USUARIO_ULTIMA_ACT  VARCHAR2(100),
    FECHA_ULTIMA_ACT    DATE
);

-- Agrega Columnas en Detalle --
ALTER TABLE BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL ADD (
    ORG_ID_INV      NUMBER,
    CODIGO_LOTE     VARCHAR2(40),
    CANTIDAD_MAX    NUMBER
);


-- Elimina Primary del Detalle --
---ALTER TABLE BODEGA.JSYB_BG_LOC_MEMO_DEVOLUCION_TL DROP CONSTRAINT JSYB_BG_ENC_LOC_MEMO_DEVOL_FK;
---ALTER TABLE BODEGA.JSYB_BG_LOD_MEMO_DEVOLUCION_TL DROP CONSTRAINT JSYB_BG_DET_LOD_MEMO_DEVOL_FK;
---ALTER TABLE BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL DROP CONSTRAINT JSYB_BG_ENC_DET_MEMO_DEVOL_FK;
ALTER TABLE BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL DROP CONSTRAINT JSYB_BG_DET_MEMO_DEVOLUCION_PK;

-- Crea Primary Remplazando Primary Original del Detalle --
ALTER TABLE BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL ADD CONSTRAINT JSYB_BG_DET_MEMO_DEVOLUCION_PK UNIQUE ( NUM_MEMO,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE );

-- Crea Foreign Cabezera-Detalle --
ALTER TABLE BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL ADD CONSTRAINT JSYB_BG_ENC_DET_MEMO_DEVOL_FK FOREIGN KEY ( NUM_MEMO,CODIGO_EMPRESA )
REFERENCES BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL ( NUM_MEMO,CODIGO_EMPRESA );

-- Crea Foreign Cabezera-Locales --
ALTER TABLE BODEGA.JSYB_BG_LOC_MEMO_DEVOLUCION_TL ADD CONSTRAINT JSYB_BG_ENC_LOC_MEMO_DEVOL_FK FOREIGN KEY ( NUM_MEMO,CODIGO_EMPRESA )
REFERENCES BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL ( NUM_MEMO,CODIGO_EMPRESA );

-- Crea Foreign Detalle-Locales --
ALTER TABLE BODEGA.JSYB_BG_LOD_MEMO_DEVOLUCION_TL ADD CONSTRAINT JSYB_BG_DET_LOD_MEMO_DEVOL_FK FOREIGN KEY ( NUM_MEMO,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE )
REFERENCES BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL ( NUM_MEMO,CODIGO_EMPRESA,ORG_ID_INV,INVENTORY_ITEM_ID,CODIGO_LOTE );


-- Inserta Locales --
--------- PENDIENTE ---------

-- Actualiza Enc --
UPDATE  BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL
    set motivo = '0',
        fecha_registro = sysdate,
        fecha_ultima_act = sysdate,
        usuario_registro = 'CARGA_INICIAL',
        usuario_ultima_act = 'CARGA_INICIAL';

-- Actualiza Det --
UPDATE  BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL
    set org_id_inv = 228;
commit;


-- Actualiza Columnas de la Cabecera Agregando Nulos y No Nulos--
ALTER TABLE BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL MODIFY (MOTIVO NOT NULL);
ALTER TABLE BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL MODIFY (USUARIO_REGISTRO NOT NULL);
ALTER TABLE BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL MODIFY (FECHA_REGISTRO NOT NULL);
ALTER TABLE BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL MODIFY (USUARIO_ULTIMA_ACT NOT NULL);
ALTER TABLE BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL MODIFY (FECHA_ULTIMA_ACT NOT NULL);

-- Agrega NO Nulos en Columnas Nuevas del Detalle --
ALTER TABLE BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL MODIFY (ORG_ID_INV NOT NULL);


-- Crea Grants de Tablas y Secuencia --
GRANT ALL ON BODEGA.JSYB_BG_NRO_MEMO_DEVOL TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_LOC_MEMO_DEVOLUCION_TL TO SYBAPPS;
GRANT ALL ON BODEGA.JSYB_BG_LOD_MEMO_DEVOLUCION_TL TO SYBAPPS;
GRANT SELECT ON BODEGA.JSYB_BG_TEMP_CAR_MEMO_DEVOL TO SYBAPPS;

-- Crea Sinonimos de Tablas y Secuencia --
CREATE SYNONYM SYBAPPS.JSYB_BG_NRO_MEMO_DEVOL FOR BODEGA.JSYB_BG_NRO_MEMO_DEVOL;
CREATE SYNONYM SYBAPPS.JSYB_BG_MEMO_DEVOLUCION_TL FOR BODEGA.JSYB_BG_MEMO_DEVOLUCION_TL;
CREATE SYNONYM SYBAPPS.JSYB_BG_DET_MEMO_DEVOLUCION_TL FOR BODEGA.JSYB_BG_DET_MEMO_DEVOLUCION_TL;
CREATE SYNONYM SYBAPPS.JSYB_BG_LOC_MEMO_DEVOLUCION_TL FOR BODEGA.JSYB_BG_LOC_MEMO_DEVOLUCION_TL;
CREATE SYNONYM SYBAPPS.JSYB_BG_LOD_MEMO_DEVOLUCION_TL FOR BODEGA.JSYB_BG_LOD_MEMO_DEVOLUCION_TL;
CREATE SYNONYM SYBAPPS.JSYB_BG_TEMP_CAR_MEMO_DEVOL FOR BODEGA.JSYB_BG_TEMP_CAR_MEMO_DEVOL;